### ISSUE TITLE
Downloading documents & flexible assets

### ISSUE THREAD

**Issue by NikhilSehgal123** [b-loyola/itglue-py#13]
How can we download documents & flexible assets using this lib?

**Comment by davidhaymond** [comment]
This library is currently incomplete and doesn't support all endpoints yet. I'll prioritize adding documents and flexible assets, and hopefully release a new version soon.

**Comment by davidhaymond** [comment]
@NikhilSehgal123 I checked the [IT Glue API documentation](https://api.itglue.com/developer#documents), and unfortunately, only updating documents is supported. There is currently no way to download existing documents.

Flexible assets, on the other hand, are already supported by this module. However, you can only get flexible assets of a single type per query. Try this:

```python
import itglue

itglue.connection.api_url = 'https://api.itglue.com' # US endpoint
itglue.connection.api_key = 'YOUR_KEY_HERE'

assets = itglue.FlexibleAsset.filter(flexible_asset_type_id=12345)
```

Let me know if that doesn't work for you.
